
name: Luiz Roselli Neto
tagline: Luiz Roselli Neto
description: Societário Novaes & Roselli Advogados
#favicon:
#  path: https://picsum.photos/64.webp
#  type: webp # File format of image. Change according to your image. Supported types: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types
logo: https://nradv.com.br/wp-content/uploads/2023/08/cropped-cropped-cropped-nradv-2x.png
url: ideiascasa.github.io/luizrneto/
locale: pt_BR
#ga4: # Google Analytics 4 measurement ID, for e.g. G-XXXXXXX (optional). Remove it if it’s not needed.
#twitter:
#  username: UserName # Used for SEO
image:
  path: https://nradv.com.br/wp-content/uploads/2023/08/cropped-cropped-cropped-nradv-2x.png # Used for SEO (og:image, twitter:image)
  type: png # File format of image.
  height: 100 # Pixels
  width: 100
  alt: logo

# Verified Badge Configuration
badge:
  enable: true # Set to 'true' or 'false' to enable / disable the badge
  icon: ri:verified-badge-fill  # Enter the icon name for the badge from Iconify Design (https://icon-sets.iconify.design/)
#  color: '#dfb221'  # Define the color of the badge
  color: '#25D366'  # Define the color of the badge

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"    


plugins:
  - jekyll-qr

# Exclude
exclude: [README.md, Gemfile.lock, .jekyll-cache/, .github/, CHANGELOG.md, Gemfile, LICENSE, vendor/, funding.yml, linkhub-jekyll-theme.gemspec]

address: |
  Av. Brigadeiro Faria Lima, 2564 - 6º andar
  São Paulo SP
  01451-000
  Brasil

social:
#  - name: facebook
#    url: https://www.facebook.com/example
#    icon: ri:facebook-fill
#    color: '#1877F2'
#
#  - name: instagram
#    url: https://www.instagram.com/example
#    icon: ri:instagram-fill
#    color: '#E4405F'
#
#  - name: x
#    url: https://x.com/example
#    icon: ri:twitter-x-fill
#    color: '#1D9BF0'
#
#  - name: mastodon
#    url: https://mastodon.social/@example
#    icon: ri:mastodon-fill
#    color: '#6364FF'

  - name: whatsapp
    url: https://wa.me/5511982543222
    icon: ri:whatsapp-fill
    color: '#25D366'

#  - name: youtube
#    url: https://www.youtube.com/@example
#    icon: ri:youtube-fill
#    color: '#FF0000'

links:
  fixed-button-width: true # Set to true/false
  icon-position: left # Set to left/right
  buttons:
    - category: Telefones
      items:
        - title: (11) 3079-5111
          url: tel:+551130795111
          icon: line-md:phone-filled

        - title: (11) 3079-5112
          url: tel:+551130795112
          icon: line-md:phone-filled

        - title: (11) 98254-3222
          url: tel:+5511982543222
          icon: line-md:cellphone
          tag: W

    - category: E-mail
      items:
        - title: lr@nradv.com.br
          url: mailto:lr@nradv.com.br

    - category: Site
      items:
        - title: nradv.com.br
          url: https://nradv.com.br/
          icon: mdi:web
          tag: Novo

#bio:
#  - name: YouTube Shorts
#    ratio: vertical # For vertical 9:16 aspect ratio. Ideal for video thumbnails, such as those used on Instagram Reels, YouTube Shorts and TikTok. To use the default 1:1 aspect ratio (square), remove this variable.
#    items:
#      - url: https://www.example.com
#        image: https://picsum.photos/1080/920.webp
#
#      - url: https://www.example.org
#        image: https://picsum.photos/540/960.webp
#
#      - url: https://www.example.com
#        image: https://picsum.photos/720/1280.webp
#
#  - name: Instagram
#    items:
#      - url: https://www.example.com
#        image: https://picsum.photos/700/400.webp # You can use paths to images in the assets folder, e.g., assets/images/insta.jpg.
#
#      - url: https://www.example.org
#        image: https://picsum.photos/500.webp
#
#      - url: https://www.example.com
#        image: https://picsum.photos/250/300.webp
